sonar.projectKey=RawProjectKey
sonar.projectName=N_Layer_Raw_Project
sonar.working.directory=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore
sonar.pullrequest.cache.basepath=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore
sonar.sources=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.vs\\SimpleBookStore\\config\\applicationhost.config",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.vs\\SimpleBookStore\\v17\\DocumentLayout.backup.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.vs\\SimpleBookStore\\v17\\DocumentLayout.json"

ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA.sonar.projectKey=RawProjectKey:ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA
ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA.sonar.projectName=SimpleBookStore.Model
ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA.sonar.projectBaseDir=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model
ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA.sonar.sourceEncoding=utf-8
ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA.sonar.tests=
ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA.sonar.sources=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\Report\\CommentCountByUserReport.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\Request\\BuyBookRequestModel.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\Request\\LoginRequestModel.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\Request\\LogRequestModel.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\Request\\RegistrationRequestModel.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\Request\\ReviewRequestModel.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\Response\\BookInfoResponseModel.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\Response\\LoginResponseModel.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\Response\\RegistrationResponseModel.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\obj\\project.assets.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\obj\\SimpleBookStore.Model.csproj.nuget.dgspec.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\bin\\Debug\\net8.0\\SimpleBookStore.Model.deps.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Model\\obj\\Debug\\net8.0\\SimpleBookStore.Model.sourcelink.json"

ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\0"
ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\0\\Issues.json"
ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA.sonar.cs.scanner.telemetry=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\0\\Telemetry.json"

ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA.sonar.working.directory=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\.sonar\\mod0
A9EA12F2-AE2A-46E9-B019-1719628ED8BE.sonar.projectKey=RawProjectKey:A9EA12F2-AE2A-46E9-B019-1719628ED8BE
A9EA12F2-AE2A-46E9-B019-1719628ED8BE.sonar.projectName=SimpleBookStore.Utility
A9EA12F2-AE2A-46E9-B019-1719628ED8BE.sonar.projectBaseDir=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Utility
A9EA12F2-AE2A-46E9-B019-1719628ED8BE.sonar.sourceEncoding=utf-8
A9EA12F2-AE2A-46E9-B019-1719628ED8BE.sonar.tests=
A9EA12F2-AE2A-46E9-B019-1719628ED8BE.sonar.sources=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Utility\\obj\\project.assets.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Utility\\obj\\SimpleBookStore.Utility.csproj.nuget.dgspec.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Utility\\bin\\Debug\\net8.0\\SimpleBookStore.Utility.deps.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Utility\\obj\\Debug\\net8.0\\SimpleBookStore.Utility.sourcelink.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.Utility\\Constant.cs"

A9EA12F2-AE2A-46E9-B019-1719628ED8BE.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\1"
A9EA12F2-AE2A-46E9-B019-1719628ED8BE.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\1\\Issues.json"
A9EA12F2-AE2A-46E9-B019-1719628ED8BE.sonar.cs.scanner.telemetry=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\1\\Telemetry.json"

A9EA12F2-AE2A-46E9-B019-1719628ED8BE.sonar.working.directory=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\.sonar\\mod1
EEA3DE2B-702B-48BE-810C-7F901DD41F19.sonar.projectKey=RawProjectKey:EEA3DE2B-702B-48BE-810C-7F901DD41F19
EEA3DE2B-702B-48BE-810C-7F901DD41F19.sonar.projectName=SimpleBookStore.DAL
EEA3DE2B-702B-48BE-810C-7F901DD41F19.sonar.projectBaseDir=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL
EEA3DE2B-702B-48BE-810C-7F901DD41F19.sonar.sourceEncoding=utf-8
EEA3DE2B-702B-48BE-810C-7F901DD41F19.sonar.tests=
EEA3DE2B-702B-48BE-810C-7F901DD41F19.sonar.sources=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\obj\\project.assets.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\obj\\SimpleBookStore.DAL.csproj.nuget.dgspec.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\bin\\Debug\\net8.0\\SimpleBookStore.DAL.deps.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\bin\\Debug\\net8.0\\SimpleBookStore.DAL.runtimeconfig.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\obj\\Debug\\net8.0\\SimpleBookStore.DAL.sourcelink.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\CommonEntity\\DbEntity.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Configurations\\DependencyResolver.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\DbContextSet\\LogContext.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\DbContextSet\\StoreContext.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\DTO\\UserBookStatsReport.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\LogEntity\\Logs.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250801142320_initial.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250801142320_initial.Designer.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250802160118_StockInSameTable.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250802160118_StockInSameTable.Designer.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250802164334_AddingRatingsModel.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250802164334_AddingRatingsModel.Designer.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250803182555_ReviewEntityFix1.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250803182555_ReviewEntityFix1.Designer.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250803182914_ReviewEntityFix2.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250803182914_ReviewEntityFix2.Designer.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250804193836_CommonEntityUpdatedDateFix.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\20250804193836_CommonEntityUpdatedDateFix.Designer.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\Log\\20250805153515_InitalLogDb.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\Log\\20250805153515_InitalLogDb.Designer.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\Log\\LogContextModelSnapshot.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Migrations\\StoreContextModelSnapshot.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Repositories\\BookRepository\\BookRepository.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Repositories\\BookRepository\\IBookRepository.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Repositories\\LogRepository\\ILogRepository.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Repositories\\LogRepository\\LogRepository.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Repositories\\ReportRepository\\IReportRepository.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Repositories\\ReportRepository\\ReportRepository.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Repositories\\ReviewRepository\\IReviewRepository.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Repositories\\ReviewRepository\\ReviewRepository.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Repositories\\UserBookRepository\\IUserBookRepository.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\Repositories\\UserBookRepository\\UserBookRepository.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\StoreEntity\\Book.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\StoreEntity\\Review.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\StoreEntity\\User.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\StoreEntity\\User_Book.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\UnitOfWork\\IStoreUnitOfWork.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.DAL\\UnitOfWork\\StoreUnitOfWork.cs"

EEA3DE2B-702B-48BE-810C-7F901DD41F19.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\2"
EEA3DE2B-702B-48BE-810C-7F901DD41F19.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\2\\Issues.json"
EEA3DE2B-702B-48BE-810C-7F901DD41F19.sonar.cs.scanner.telemetry=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\2\\Telemetry.json"

EEA3DE2B-702B-48BE-810C-7F901DD41F19.sonar.working.directory=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\.sonar\\mod2
0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6.sonar.projectKey=RawProjectKey:0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6
0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6.sonar.projectName=SimpleBookStore.BLL
0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6.sonar.projectBaseDir=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL
0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6.sonar.sourceEncoding=utf-8
0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6.sonar.tests=
0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6.sonar.sources=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\obj\\project.assets.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\obj\\SimpleBookStore.BLL.csproj.nuget.dgspec.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\bin\\Debug\\net8.0\\SimpleBookStore.BLL.deps.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\obj\\Debug\\net8.0\\SimpleBookStore.BLL.sourcelink.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\Configurations\\DependencyResolver.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\Services\\BookService\\BookService.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\Services\\BookService\\IBookService.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\Services\\LogService\\ILogService.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\Services\\LogService\\LogService.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\Services\\ReportService\\IReportService.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\Services\\ReportService\\ReportService.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\Services\\ReviewService\\IReviewService.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\Services\\ReviewService\\ReviewService.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\Services\\UserService\\IUserService.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore.BLL\\Services\\UserService\\UserService.cs"

0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\3"
0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\3\\Issues.json"
0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6.sonar.cs.scanner.telemetry=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\3\\Telemetry.json"

0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6.sonar.working.directory=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\.sonar\\mod3
E20FDFA2-A898-46E0-B5AB-10BBD335296B.sonar.projectKey=RawProjectKey:E20FDFA2-A898-46E0-B5AB-10BBD335296B
E20FDFA2-A898-46E0-B5AB-10BBD335296B.sonar.projectName=SimpleBookStore
E20FDFA2-A898-46E0-B5AB-10BBD335296B.sonar.projectBaseDir=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore
E20FDFA2-A898-46E0-B5AB-10BBD335296B.sonar.sourceEncoding=utf-8
E20FDFA2-A898-46E0-B5AB-10BBD335296B.sonar.tests=
E20FDFA2-A898-46E0-B5AB-10BBD335296B.sonar.sources=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\appsettings.Development.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\appsettings.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\obj\\project.assets.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\obj\\SimpleBookStore.csproj.nuget.dgspec.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\Properties\\launchSettings.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\bin\\Debug\\net8.0\\SimpleBookStore.deps.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\bin\\Debug\\net8.0\\SimpleBookStore.runtimeconfig.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\obj\\Debug\\net8.0\\ApiEndpoints.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\obj\\Debug\\net8.0\\SimpleBookStore.sourcelink.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\Controllers\\AccountController.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\Controllers\\BookController.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\Controllers\\ReportController.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\Controllers\\ReviewController.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\CustomFiltering\\AuthorizationFilter.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\Program.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\WeatherForecast.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\obj\\Debug\\net8.0\\SimpleBookStore.GlobalUsings.g.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\obj\\Debug\\net8.0\\SimpleBookStore.AssemblyInfo.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\obj\\Debug\\net8.0\\SimpleBookStore.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\.gitignore",\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\SimpleBookStore\\SimpleBookStore.http"

E20FDFA2-A898-46E0-B5AB-10BBD335296B.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\4"
E20FDFA2-A898-46E0-B5AB-10BBD335296B.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\4\\Issues.json"
E20FDFA2-A898-46E0-B5AB-10BBD335296B.sonar.cs.scanner.telemetry=\
"C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\4\\Telemetry.json"

E20FDFA2-A898-46E0-B5AB-10BBD335296B.sonar.working.directory=C:\\Users\\BS01389\\source\\repos\\SimpleBookStore\\.sonarqube\\out\\.sonar\\mod4
sonar.host.url=http://localhost:9000
sonar.exclusions=**/Migrations/*.cs
sonar.visualstudio.enable=false

sonar.modules=ED33CEB9-8CD0-4C5D-8B29-F5EFCD255CBA,A9EA12F2-AE2A-46E9-B019-1719628ED8BE,EEA3DE2B-702B-48BE-810C-7F901DD41F19,0874DA87-C6DD-40E4-AE5B-71D61F6CB7B6,E20FDFA2-A898-46E0-B5AB-10BBD335296B

