<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KhatiExtendedAdo" Version="8.0.6" />
    <PackageReference Include="KhatiExtendedEF" Version="8.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleBookStore.Model\SimpleBookStore.Model.csproj" />
    <ProjectReference Include="..\SimpleBookStore.Utility\SimpleBookStore.Utility.csproj" />
  </ItemGroup>

</Project>
